### ISSUE TITLE
zabbix安装DBforbix监控oracle 11g

### ISSUE THREAD

**Issue by john5480** [john5480/test#57]
# zabbix安装DBforbix监控oracle 11g

环境：
RHEL 7.2
zabbix 3.4 + mysql 5.7.20
openJDK 1.8.0

[zabbix share][1] 推荐了几个oracle监控模板，DBforBIX是orabix扩展版，或者已经停止更新。zabbixDBA作者自06年上了以后没更新过，不太敢用；pyora要在每台被监控oracle安装python库，不如并且项目不如DBforBIX全，但是改起来比较方便。最终选用DBforBIX。

1.客户端数据库创建zabbix用户和相应权限：
```
 CREATE USER ZABBIX
  IDENTIFIED BY <REPLACE WITH PASSWORD>
  DEFAULT TABLESPACE SYSTEM
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -– 2 Roles for ZABBIX
  GRANT CONNECT TO ZABBIX;
  GRANT RESOURCE TO ZABBIX;
  ALTER USER ZABBIX DEFAULT ROLE ALL;
  –- 5 System Privileges for ZABBIX
  GRANT SELECT ANY TABLE TO ZABBIX;
  GRANT CREATE SESSION TO ZABBIX;	
  GRANT SELECT ANY DICTIONARY TO ZABBIX;
  GRANT UNLIMITED TABLESPACE TO ZABBIX;
 GRANT SELECT ANY DICTIONARY TO ZABBIX;
 exec dbms_network_acl_admin.create_acl(acl => ‘resolve.xml’,description => ‘resolve acl‘, principal =>’ZABBIX’,is_grant => true, privilege => ‘resolve’);
  exec dbms_network_acl_admin.assign_acl(acl => ‘resolve.xml’, host =>’*');
``` 

2. 先到 [github 主页][2] 下载安装包，代码包只需下载 [dist][3] 目录下的文件。然后解压到zabbix服务器上的`/opt/dbforbix`目录，一定要解压到这个目录，因为代码和脚本是写死的，改起来比较麻烦。
![image.png-81kB][4]
3. 修改`conf/config.properties`文件，请看以下示例：
```
DBforBIX.UpdateConfigTimeout=120
Pool.LoginTimeOut=15
ZabbixServer.Zabbix1.Address=127.0.0.1 # zabbix服务器地址
ZabbixServer.Zabbix1.Port=10051        # zabbix服务器端口
# 代理程序名称，要在web界面同配置
ZabbixServer.Zabbix1.ProxyName=DBforBIX  
ZabbixServer.Zabbix1.ConfigSuffix=DBforBIX.config

# 被监控的数据库列表清单，要在web界面同配置
ZabbixServer.Zabbix1.DBList=ORADB1 

# 被监控的数据库列表详情
DB.ORADB1.Type=oracle
DB.ORADB1.Instance=tbzhs
DB.ORADB1.Url=jdbc:oracle:thin:@10.1.0.84:1521:tbzhs
DB.ORADB1.User=zabbix
DB.ORADB1.Password=zabbix
DB.ORADB1.MaxActive=10
DB.ORADB1.MaxWaitMillis=10000
DB.ORADB1.QueryTimeout=15
DB.ORADB1.MaxIdle=1
```
修改后回头检查
3. 打开zabbix web管理界面，管理-> 一般 -> 宏，添加宏`{$DSN}`，值`ORADB1`，这里与上面配置文件中`ZabbixServer.Zabbix1.DBList`参数值相同，值为`ORADB1`
![image.png-24.3kB][5]
4. 管理->agent代理程序->创建代理，这里的值与上面配置文件中`ZabbixServer.Zabbix1.ProxyName`参数值要相同，值为`DBforBIX`
![image.png-36.3kB][6]
5. 配置->模板->导入，选择模板导入，注意这里是选择`DBforBIX/zbx_templates/zbx_template_DBforBIX.Oracle.Instances.xml`和`zbx_template_DBforBIX.Oracle.ASM.xml`，还有个mysql的有需要也可以导。完成后打开模板界面会发现监控项很少，是因为大部分监控项通过自动发现加上的。
![image.png-49.9kB][7]
 6. 配置->主机->添加主机群组，添加一个DBforBIX群组
 7. 配置->主机->添加主机，创建你要监控的数据库，agent代理就是上面参数文件和刚刚创建的agent代理程序
![image.png-72kB][8]

添加dbforbix模板，有ASM加ASM模板
![image.png-27.6kB][9]

添加宏
![image.png-22.6kB][10]
8. 加完以后回到zabbix服务器，切换到`/opt/dbforbix`，可以后台执行`nohup sh dbforbix.sh &`进行测试，如果刷出如果`nohup.out`中刷出大量日志说明成功了。如果被监控数据库是11g，其中`Error message:ORA-00904:"SQL_FULL_PLAN_HASH_VALUE": invalid identifier`报错，
不用管，因为这是12c参数。
9. 等1-3分钟，web界面的监控项已经出现了。

探索中还发现两个问题：
1. 触发器只有关于表空间的，而没有lock,latch,sga类告警；
2. 注册systemd服务启动时，会报错超时，已经向作者求证，等待后续结果。
[求证页面][11]
3. 另外还发现无法监控到archivelog日志大小

参考资料：
数据库配置：
http://www.smartmarmot.com/wiki/index.php?title=DBforBIX2
服务器和参数说明：
https://github.com/smartmarmot/DBforBIX/wiki/New-DBforBIX-as-Zabbix-Proxy
中文文档:
https://wenku.baidu.com/view/d27c20e4fbb069dc5022aaea998fcc22bcd14361.html?from=search

  [1]: https://share.zabbix.com/databases/oracle
  [2]: https://github.com/smartmarmot/DBforBIX
  [3]: https://github.com/smartmarmot/DBforBIX/tree/master/dist
  [4]: http://static.zybuluo.com/gaoxiaoyunwei2017/h50etd4ahuni79ye9wjn2twc/image.png
  [5]: http://static.zybuluo.com/gaoxiaoyunwei2017/fc41l33ss501aav8ji39juhd/image.png
  [6]: http://static.zybuluo.com/gaoxiaoyunwei2017/g81zjqm1xj3t7w3hax84tof4/image.png
  [7]: http://static.zybuluo.com/gaoxiaoyunwei2017/qyx2u84c76dazbiuh5aoui1l/image.png
  [8]: http://static.zybuluo.com/gaoxiaoyunwei2017/45oncl5r57k7w4p52c1pyorz/image.png
  [9]: http://static.zybuluo.com/gaoxiaoyunwei2017/6t75ho4aerhyd26m5hm4fnci/image.png
  [10]: http://static.zybuluo.com/gaoxiaoyunwei2017/wis3c5dcae11384rfwdcu8nw/image.png
  [11]: https://github.com/smartmarmot/DBforBIX/issues/55

**Comment by aceslup** [comment]
@john5480 兄嘚，dbforbix怎么启动？dist中的包没启动脚本啊。外面的dbforbix.sh启动的是dbforbix_run.jar啊。你弄的不是3.0版本吧。

**Comment by oraclecaicai** [comment]
> 
> 
> @john5480 兄嘚，dbforbix怎么启动？dist中的包没启动脚本啊。外面的dbforbix.sh启动的是dbforbix_run.jar啊。你弄的不是3.0版本吧。

正在搞dbforbix，发现3.0版本的包里缺很多东西，要从项目的其它目录里找，很是麻烦。2.4版本的包里的东西更全一些，如果不行就换旧版本了。
